(setq php-mode-coding-style (quote psr2))
(require 'php-mode)
(scroll-bar-mode -1)
(add-to-list 'auto-mode-alist '("\\.php$" . php-mode))
(add-hook 'php-mode-hook
          (lambda ()
            (setq flycheck-phpcs-standard "PSR2")
            (c-set-offset 'case-label 4)
            (c-set-offset 'arglist-intro 4)
            (c-set-offset 'arglist-cont-nonempty 4)
            (c-set-offset 'arglist-close 0)))
